/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
		AButton: typeof import('ant-design-vue/es')['Button']
    AppLoading: typeof import('./../components/common/app-loading.vue')['default']
    BetterScroll: typeof import('./../components/custom/better-scroll.vue')['default']
    CountTo: typeof import('./../components/custom/count-to.vue')['default']
    DarkModeContainer: typeof import('./../components/common/dark-mode-container.vue')['default']
    DarkModeSwitch: typeof import('./../components/common/dark-mode-switch.vue')['default']
    ExceptionBase: typeof import('./../components/common/exception-base.vue')['default']
    GithubLink: typeof import('./../components/custom/github-link.vue')['default']
    HoverContainer: typeof import('./../components/common/hover-container.vue')['default']
    IconSelect: typeof import('./../components/custom/icon-select.vue')['default']
    ImageVerify: typeof import('./../components/custom/image-verify.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
    WebSiteLink: typeof import('./../components/custom/web-site-link.vue')['default']
  }
}
